### PR TITLE
Some changes from my fork

### PR DESCRIPTION
**Pull request by Vap0r1ze**
I made a fork that has a few fixes for things that were causing issues with a project of mine. Figured I'd open a PR to see which changes you'd be willing to merge:
  - corrected the order in which `settings` were `concat`ed in themes that `include`d others
  - import [json5](https://github.com/json5/json5) to parse json files with comments
  - preserved the `colors` property in themes
  - exposed [Highlighter#getTheme](https://github.com/shikijs/shiki/blob/c838ebcf7e7ab419fc10a6a9cfc83d9236c8e1e0/packages/shiki/src/highlighter.ts#L58-L66)

### CODE REVIEW

**Comment by Vap0r1ze** [comment]
Not sure what the deal with the lockfile is

**Comment by octref** [comment]
font style is already supported through another PR. I'm doing a rebase for your changes. They all look good to me. Thanks for your contribution!

**Comment by octref** [comment]
I agree with all changes except exposing `colors`. Users have no idea how to use the `colorMap`. Do you want to open another issue to discuss? I'll leave that out for now and merge your changes.
My thinking is if we were to expose it, then give it proper documentation and usage instructions.

**Comment by octref** [comment]
I just found that you maintain https://github.com/Vap0r1ze/vpc-shiki. Can I add it to readme?

**Comment by Vap0r1ze** [comment]
> I just found that you maintain https://github.com/Vap0r1ze/vpc-shiki. Can I add it to readme?

Yes of course you can!

**Comment by Vap0r1ze** [comment]
> I agree with all changes except exposing `colors`. Users have no idea how to use the `colorMap`. Do you want to open another issue to discuss? I'll leave that out for now and merge your changes.

I don't have any use case for using `colorMap`, so I won't be able to discuss that.

**Pull request merged**
