### PR TITLE
fix: add 'cs' alias for csharp and 'fs' alias for fsharp

### PR DESCRIPTION
**Pull request by mysticmind**
- ~~Add a test if possible~~
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by orta** [comment]
Yeah, I think this makes sense 👍🏻

**Comment by emersonbottero** [comment]
Hi @mysticmind . Could you redo the same PR?
thanks 🙂

**Comment by mysticmind** [comment]
@emersonbottero Redoing the PR is not going to help since the bot will overwrite it again. Let me dig deeper to see if I could make things work with the bot setup.

**Comment by mysticmind** [comment]
@emersonbottero Added a PR https://github.com/shikijs/shiki/pull/353.

**Pull request merged**
