### PR TITLE
chore: update deps

### PR DESCRIPTION
**Pull request by antfu**
PR for CI

### CODE REVIEW

**Comment by orta** [comment]
I have access to netlify, but maybe the `netify.toml` allows setting the node version?

**Comment by antfu** [comment]
Yes, I was interpreted by other stuff, should be good now

**Comment by antfu** [comment]
Btw, netlify does not triggered since the change for branch name. Will need a re-link I think.

**Comment by orta** [comment]
oh boo

**Comment by orta** [comment]
That will require @octref - I think we should tread on and I'll make an issue about it

**Pull request merged**
