### PR TITLE
add note on where to preview themes

### PR DESCRIPTION
**Pull request by sw-yx**
just adding a note since its a natural question to ask :)

### CODE REVIEW

**Comment by octref** [comment]
Is that technically correct though? I cannot preview dark-plus or light-plus, for example.

**Comment by sw-yx** [comment]
ah. oops. perhaps we can say you can preview *some* of these themes?

also wondering what are your thoughts for allowing people to bring their own themes?

**Comment by octref** [comment]
@sw-yx That is already possible, see https://shiki.matsu.io

image

**Review by octref — APPROVED** [review]
LGTM, thanks 👍

**Pull request merged**
