### PR TITLE
fix: add 'cs' alias for csharp and 'fs' alias for fsharp

### PR DESCRIPTION
**Pull request by mysticmind**
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by mysticmind** [comment]
@octref Appreciate if you could take a look at this PR and merge it accordingly. Note that in https://github.com/shikijs/shiki/pull/323, I had provided a PR to fix this and was merged, looks like with the recent script based automation, the change got removed. This PR re-adds it and will work fine with the automation.

**Comment by mysticmind** [comment]
This PR also fixes https://github.com/shikijs/shiki/issues/331

**Comment by orta** [comment]
Cool, looks good to me 👍🏻 thanks

**Comment by mysticmind** [comment]
> Cool, looks good to me 👍🏻 thanks

Thank you!

**Pull request merged**
