### PR TITLE
feat: support custom elements for html renderer

### LINKED ISSUE #220: Custom <pre> / <code> attributes
Please consider a way to add custom attributes on `pre` / `code` elements. Some usecases:

- **Keyboard navigation of codeblocks**: To make the codeblocks accessible for keyboard users, `tabindex = "0"` should be set on `pre` element so that they can scroll them with keyboard. As a short-term goal, we can add `tabindex = "0"` by default. In long-term, we can still keep `tabindex="0"` as default but allow people to customize it. More details can be found here: https://accessibilityinsights.io/info-examples/web/scrollable-region-focusable/
- **Adding [data-*] attributes** for customizing the behavior of codeblocks, e.g., adding a "Copy to Clipboard" button for specific codeblocks, displaying codeblock title, language, etc.

### PR DESCRIPTION
**Pull request by fengzilong**
- [x] Add a test if possible
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

- [x] This PR fixes #220

### CODE REVIEW

**Comment by kylebutts** [comment]
I'm a really big fan of this! This would make my workflow much easier than find and replacing things :-)

**Comment by jrson83** [comment]
Please merge this PR!

**Comment by a-trost** [comment]
This would be fantastic for being able to display what language a code block is showing.

**Comment by fengzilong** [comment]
The merge conflicts were solved

**Comment by orta** [comment]
OK, I'm making an executive call on this - I think this is a pretty solid abstraction, and allows for people to be able to work around many cases with a single set of tools. I think this is one we should have in WRT #220

**Pull request merged**
