### PR TITLE
refactor(cli): code-to-ansi

### PR DESCRIPTION
**Pull request by Simon-He95**

### CODE REVIEW

**Comment by antfu** [comment]
Do you have an issue regarding this? I guess that bold and italic can exist at the same time

**Comment by Simon-He95** [comment]
> Do you have an issue regarding this? I guess that bold and italic can exist at the same time您对此有什么问题吗？我想粗体和斜体可以同时存在

`token.fontStyle` is impossible to satisfy both `FontStyle.Bold` and `FontStyle.Italic` at the same time

**Comment by antfu** [comment]
Actually it's a bug in another way: we need to use AND to do bitwis comparison:

https://github.com/shikijs/shiki/blob/2d58f7ff7bd642682e93b577d9b68bede8548ef8/packages/core/src/utils.ts#L202-L209

**Comment by Simon-He95** [comment]
> Actually it's a bug in another way: we need to use AND to do bitwis comparison:实际上，从另一个方面来说，这是一个错误：我们需要使用 AND 来做 bitwis 比较：
> 
> https://github.com/shikijs/shiki/blob/2d58f7ff7bd642682e93b577d9b68bede8548ef8/packages/core/src/utils.ts#L202-L209

My mistake. I ignored text as the next parameter.

**Pull request closed without merging**
