### PR TITLE
feat: Add support for CodeQL language

### PR DESCRIPTION
**Pull request by jorgectf**
*[CodeQL](https://codeql.github.com/) is the analysis engine used by developers to automate security checks, and by security researchers to perform variant analysis.*

*In CodeQL, code is treated like data. Security vulnerabilities, bugs, and other errors are modeled as queries that can be executed against databases extracted from code. You can run the standard CodeQL queries, written by GitHub researchers and community contributors, or write your own to use in custom analyses. Queries that find potential bugs highlight the result directly in the source file.* 

See [documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)

- [x] I have read docs for [adding a language](/docs/languages.md#adding-grammar).
- [x] I have searched around and this is the most up-to-date, actively maintained version of the language grammar.
- [x] I have added a sample file that includes a variety of language syntaxes and succinctly captures the idiosyncrasy of a language. See [docs](/docs/languages.md#adding-grammar) for requirement.

### CODE REVIEW

**Comment by orta** [comment]
Do you have a grammar source for this so it will auto-update? https://github.com/shikijs/shiki/blob/main/scripts/grammarSources.ts

**Comment by jorgectf** [comment]
> Do you have a grammar source for this so it will auto-update? https://github.com/shikijs/shiki/blob/main/scripts/grammarSources.ts

Done :) I think it got removed while reverting commits to apply [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by orta** [comment]
Thanks

**Comment by jorgectf** [comment]
> Thanks

Thank you for the merge!

**Pull request merged**
