### PR TITLE
fix: update grammar resource locations

### PR DESCRIPTION
**Pull request by KevinBatdorf**
This PR updates the grammar file locations that have changed.  All the code changes outside of `scripts/grammarSources.ts` is auto generated by running `pnpm update:grammars`

I'm not sure the astro url is correct? Can yml files be used here? They changed it on this commit: https://github.com/withastro/language-tools/commit/986a23021213f7d0239e3f6a9b757228f21e43be

### CODE REVIEW

**Comment by octref** [comment]
It seems they just do `"build:grammar": "npx js-yaml syntaxes/astro.tmLanguage.src.yaml > syntaxes/astro.tmLanguage.json"`. I'm fine for either adding `yml` support, or you can use `marketplaceGrammarSources`.

**Comment by KevinBatdorf** [comment]
Would you mind taking over the PR? I added this but it didn't seem to compile for me. I also tried `extensions/syntaxes/astro.tmLanguage.json` too but no change.

```js
export const marketplaceGrammarSources: { [extPublisherAndId: string]: [string, string][] } = {
  'bpruitt-goddard.mermaid-markdown-syntax-highlighting': [
    ['mermaid.tmLanguage.json', 'extension/out/mermaid.tmLanguage.json']
  ],
  'astro-build.astro-vscode': [['astro.tmLanguage.json', 'syntaxes/astro.tmLanguage.json']]
}
```

I tried deleting `shiki/languages/*` as well and running `pnpm update:grammars` command, and both astro and mermaid language files were not added back, so there may be an issue in general with me accessing the vs code marketplace (it also stalled took 15 minutes for the script to run)

**Comment by octref** [comment]
Sorry, I think the confusion comes from my comment not being clear. It should be the path in `~/.vscode/extensions/<extid>/<path>`. I'll fix it in the PR

**Comment by octref** [comment]
Thanks for your contribution 🚀

**Comment by KevinBatdorf** [comment]
Ah, I didnt realize it was actually pulling them from a local spot. So I would need to save the file into my `~/.vscode/extensions/` directory. The comment you added helps. 

> Thanks for your contribution 

I'll see what I can contribute toward the 1.0 roadmap as well!

**Comment by octref** [comment]
@KevinBatdorf After you run the script, see the `tmp` folder in your `shiki` project. It's downloading and pulling it from there.

**Comment by KevinBatdorf** [comment]
ok i'll investigate why its not working for me. The code change you made was one I tried previously as well.

**Comment by octref** [comment]
The logic is
- Download ext binary from marketplace
- Extract it to `./tmp`
- Copy it from `./tmp/<ext>/extension/...` to `./tmp/grammars`

You can just look into your local `./tmp` in the shiki project to see what's going on.

**Comment by KevinBatdorf** [comment]
Yeah it looks like this is just failing locally for me for some reason. I'll debug over the weekend and see if there anything of interest to share. 

```js
await get(getMarketplaceLink(extFullId), 'binary')
```

Screen Shot 2023-01-26 at 8 03 15 PM

**Comment by octref** [comment]
Thanks! Also pushed a change to make it simpler: https://github.com/shikijs/shiki/commit/391713be6dec7b9484b06da0bc5bf27c33e5fee6#diff-d1a6a97ac0c73b3df23cfca0356563e1adca2c7a155e975c9c70a0dcf0e04369

**Pull request merged**
