### PR TITLE
Add "css-variables" theme, support dark mode

### PR DESCRIPTION
**Pull request by FredKSchott**
- Adds local "css-variables.json" theme
- Adds documentation for this theme, and dark mode support in general
    - (feel free to make any changes to docs as you see fit!)
- Closes (potentially) #33 ?

### CODE REVIEW

**Comment by FredKSchott** [comment]
@orta alright, I got a new implementation working for this PR, now assuming the VSCode bug does not get fixed. If we think it might get fixed, we can revert back to the original theme.

The new implementation is essentially a more controlled take on @pveyes's original approach to hex->variable mapping. The new theme uses valid hex color code as unique identifiers (`#000001`, `#000002`, `#000003`, etc) to get around the VSCode limitation. Once the theme has been loaded and we have the color map (`_colorMap = ['#000001', '#000002', ...`) we can replace those with the matching CSS variable that we care about.

Let me know if this is acceptable. I don't _love_ doing the hex->var mapping, but since we have direct access to `_colorMap` after the theme is parsed the "fix" step is actually pretty lightweight. 

If this method isn't acceptable, then I think we're blocked by the limitation linked to above, and I'll probably just go ahead with this solution in user-land (already implemented in Astro in https://github.com/snowpackjs/astro/pull/1208)

**Comment by antfu** [comment]
That's an interesting workaround! Nice idea! I am good with it 👍

**Comment by orta** [comment]
I agree, given that it's all happening internally, I don't think it's too hacky of an answer

**Comment by FredKSchott** [comment]
Great, glad this makes sense. In that case, the PR is ready to merge on my end!

**Comment by orta** [comment]
Should be shipped as 0.9.9

**Comment by octref** [comment]
Thanks for your contribution @FredKSchott! Please take a look at https://github.com/shikijs/shiki/issues/33#issuecomment-921229816 though.

**Pull request merged**
