### PR TITLE
fix: Use WASM in non-browser environments

### PR DESCRIPTION
**Pull request by jeffrey-ng**
- [x] Format all commit messages with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

### CODE REVIEW

**Comment by orta** [comment]
I think this PR probably needs a bit of context (as there's no PR body) what are your goals?

**Comment by pengx17** [comment]
I too encounter a problem when integrating shika into the new [App directory feature](https://beta.nextjs.org/docs/routing/fundamentals) in Next.js 13. 
It seems that when invoking `shiki.getHighlighter` in a [`generateStaticParams` call](https://beta.nextjs.org/docs/api-reference/generate-static-params), it is actually running in the Webpack context that has a custom `require`. See a similar issue here https://github.com/webpack/webpack/issues/9393. 

I have no clue why Nextjs is doing this, but I suppose the Nextjs team wants to have the server code bundled as well so that the runtime on Edge could be minimized/optimized.

**Comment by ishaba** [comment]
Looks like i also will fix my issue with nuxt any updates on this?

**Comment by octref** [comment]
Is this still an issue, @pengx17?

**Comment by pengx17** [comment]
> Is this still an issue, @pengx17?

I just [reworked](https://github.com/pengx17/next-blog-neo/commit/fca039227ec821fe25a7ea5898e13e0536877aa6#commitcomment-98383609) my blog and rendering code blocks directly inside of React server components. Shiki works perfectly in this case. 👯 
I guess my original issue was that I should not call shiki inside of [generateStaticParams](https://beta.nextjs.org/docs/api-reference/generate-static-params). I am not too sure if it was still an issue.

Thanks for providing this awesome project!

**Comment by octref** [comment]
Great, I'll close this then. There's a sample for next + shiki now: https://github.com/shikijs/next-shiki

**Comment by samselikoff** [comment]
@octref just came across this issue! I tried the `next-shiki` sample you posted using Vercel's `experimental-edge` runtime and I'm hitting a similar wasm error:

image

I'm a bit out of my league here as I haven't spent a lot of time on this but just curious if shiki should be able to work in the edge-runtime? Thanks for any pointers!

**Comment by pengx17** [comment]
@samselikoff I think the reason of the error is that non-module (json here) in `node_modules` will not be bundled into the edge runtime. I am not sure if there is a graceful way to fix this issue, but my solution is to copy/paste shiki resource files (/themes, /lanague) under the next repo, and then configure shiki to point to the files in the repo instead of using the default path:
See https://github.com/pengx17/next-blog-neo/blob/main/app/lib/rehype-shiki.ts#L16-L17

**Pull request closed without merging**
