### PR TITLE
docs: pass CodeBlock/highlight code + lang in as props, parameter

### PR DESCRIPTION
**Pull request by karlhorky**
### Description

Pass in:

1. code and language via props for `<CodeBlock>` component
2. language via 2nd `highlight()` function parameter

### Linked Issues

--

### Additional context

--

### CODE REVIEW

**Comment by antfu** [comment]
Could you help to fix the lint? Thanks

**Comment by karlhorky** [comment]
Sure thing - what do you think of the style in this commit:

- da2d7da4846dcf3706a7f67ccc42453ec1e71d6d

**Comment by antfu** [comment]
It's just some demo examples; I think it's fine either way, but I would think it's better not to involve too many concepts all at once. It shouldn't be hard for developers to catch up and fix it, it's a problem unrelated to Shiki so I think it's better to not mention that. I changed it to array join to workaround that.

**Comment by karlhorky** [comment]
Sounds good, thanks for the review, edit and merge!

**Pull request merged**
