### PR TITLE
feat: slack themes

### LINKED ISSUE #75: Add "slack" themes
I would like to integrate slack themes
https://github.com/slack-theme/visual-studio-code

My blog is using them with `gatsby-remark-vscode` at the moment, and i'm in the process of upgrading to `shiki`. Amongst the things i'm missing, this seems like an easy fix.

Will open a PR! 😀

### PR DESCRIPTION
**Pull request by codepunkt**
Fixes #75

### CODE REVIEW

**Comment by octref** [comment]
Sorry, I just realized that I didn't finish the script. Can you rebase off master and run `yarn:update-themes` again?
Also, why only choose two of the themes?

**Comment by codepunkt** [comment]
Wasn't sure how many you'd want. Those are the two that i'm using. I can add all of them for a better/full experience. Should i?

**Comment by octref** [comment]
Can you please only add `ochin`? I think all the themes have same syntax highlighting, just different workspace colors.
Aubergine dark is the only one with different syntax highlighting, but it doesn't look that good to me.

**Comment by codepunkt** [comment]
That doesn't fit my usecase. I need two of them, and a good solution to switch between them for light/dark mode.

If this is not mergeable here, i'll use my fork.

**Comment by octref** [comment]
There's a script to update theme source https://github.com/shikijs/shiki/blob/master/scripts/pullGHThemes.sh#L6

I rebased off origin/master and made the necessary changes.

**Review by octref — APPROVED** [review]

**Comment by codepunkt** [comment]
Awesome, thanks @octref! 👍 
Whenever you decide you'd also want to have the other Slack themes, i can do that.

**Pull request merged**
